name: AWSDeploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone repositorys with git
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.ip}}
        USERNAME: ${{ secrets.usuario}}
        PORT: ${{ secrets.porta}}
        KEY: ${{ secrets.chave}}
        script: |
            cd ./repo/api/api-preco-acoes
            sudo git pull origin
            sudo mvn clean package
  executing:
    runs-on: ubuntu-latest

    steps:
  
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.ip}}
        USERNAME: ${{ secrets.usuario}}
        PORT: ${{ secrets.porta}}
        KEY: ${{ secrets.chave}}
        script: |
            cd ./repo/api/api-preco-acoes
            sudo docker kill apir
            sudo docker rmi api
            sudo docker build . -t api
            sudo docker run --name apir -d --rm -p 80:80 api
            sudo docker logs apir